apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
data:
  rules.yaml: |
    groups:
      - name: kubearmor_alert
        rules:
          - alert: KubeArmorPolicyAction
            expr: sum by(policyName) (rate({exporter="OTLP"} | json policyName="body.PolicyName" [5m])) > 0
            for: 1m
            labels:
                severity: warning
            annotations:
                summary: Audit/Block action for a kubearmor policy
                message: 'Audit/Block action for a kubearmor policy: `{{ $labels.policyName }}`'

